spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.defaultCatalog=iceberg
spark.sql.catalog.iceberg=org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.iceberg.type=rest
spark.sql.catalog.iceberg.uri=http://iceberg-rest:8181
spark.sql.catalog.iceberg.io-impl=org.apache.iceberg.aws.s3.S3FileIO
spark.sql.catalog.iceberg.s3.endpoint=http://minio:9000
spark.sql.catalog.iceberg.s3.path-style-access=true
spark.sql.catalog.iceberg.client.region=us-east-1
spark.sql.sources.partitionOverwriteMode=dynamic
spark.driver.memory=2g
spark.jars.ivy=/tmp/.ivy
spark.sql.iceberg.vectorization.enabled=false
spark.sql.session.timeZone=Etc/UTC
